# Generated by Django 5.1.1 on 2024-10-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='source',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('UPLOAD', 'Manual Upload')], default='UPLOAD', max_length=10),
        ),
    ]
