# Generated by Django 5.1.1 on 2024-10-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_invoice_invoice_date_invoice_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='processing_errors',
            field=models.TextField(blank=True, null=True),
        ),
    ]
